services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_URL
        value: sqlite:///chatbot.db
